services:

    controller.blog:
        class: 'Tech387\Presentation\Controller\AdminController'
        arguments: ['@service.admin', '@service.blog', '@service.newsletter','@service.auth']
        
    controller.auth:
        class: 'Tech387\Presentation\Controller\AuthController'
        arguments: ['@service.auth']

    controller.faq:
        class: 'Tech387\Presentation\Controller\FaqController'
        arguments: ['@service.faq','@service.auth']
