services:

    controller.blog:
        class: 'Tech387\Presentation\Controller\AdminController'
        arguments: ['@service.admin', '@service.blog', '@service.newsletter']
        
    controller.auth:
        class: 'Tech387\Presentation\Controller\AuthController'