blog.user.admin:
    path: /{controller}{slash}
    defaults:
        action: post
    requirements:
        id: "[1-9][0-9]*"
        slash: "[/]{0,1}"
    methods: [GET, POST]

blog.admin:
    path: /{controller}/{id}{slash}
    defaults:
        action: post
    requirements:
        id: "[1-9][0-9]*"
        slash: "[/]{0,1}"
    methods: [PUT, DELETE]

blog.action.single:
    path: /{controller}/{action}{slash}
    requirements:
        id: "[1-9][0-9]*"
        slash: "[/]{0,1}"
    methods: [POST,GET]

