parameters:
    tables:
        conversations:
            primary:            '`Conversations`'
            participants:       '`ConversationParticipants`'
            messages:           '`ConversationMessages`'

        participants:           '`Participants`'

        messages:               '`Messages`'
